### ISSUE TITLE
Be in state of suspended animation after click the menu ‘configure handy menu’

### ISSUE THREAD

**Issue by Nat30** [sergeishere/HandyMenu-SketchPlugin#10]
Be in state of suspended animation after click the menu ‘configure handy menu’.  Also can't open sketch plugins manager. 

Sketch version: 50.2
Handy menu version: 4.1

**Comment by sergeishere** [comment]
@Nat30 Thanks for feedback, I will check it

**Comment by Nat30** [comment]
I just test in Sketch 51. The issue is still there. Also i uninstall all the other plugins and just keep handy menu, it still can't work.

**Comment by Nat30** [comment]
<img width="1599" alt="qq20180711-095424 2x" src="https://user-images.githubusercontent.com/26952349/42546520-4e207a30-84f0-11e8-8eec-5c0d5fcfd8cb.png">
This is what's the suspended animation looks like.

**Comment by golevkadesign** [comment]
Same issue as mine, when v49 to v51.1

**Comment by Nat30** [comment]
High Sierra 10.13.6 (17G65)

**Comment by sergeishere** [comment]
@Nat30 @golevkadesign Pls, test it in the latest (v5) version.
