### ISSUE TITLE
Scroll to first match doesn't always work

### ISSUE THREAD

**Issue by aparajita** [sergeishere/HandyMenu-SketchPlugin#12]
Try the following:

- Open the configure dialog.
- Manually scroll down the list on the left.
- Type in the search field.

The first matching item is not scrolled into view. If the list was scrolled to the top when the search started, it is scrolled into view.

**Comment by sergeishere** [comment]
Thanks for noticing! Will be fixed in the v5.1

**Comment by sergeishere** [comment]
Fixed in v5.1
