### ISSUE TITLE
sketch 52.1 broken

### ISSUE THREAD

**Issue by morgancheung** [sergeishere/HandyMenu-SketchPlugin#14]

**Comment by sergeishere** [comment]
@morgancheung Have you restarted Sketch after installing?

**Comment by sergeishere** [comment]
hmm...no crashes, just does not launch? Could you launch the settings window through Plugins menu? Plugins -> Handy Menu -> Configure...

**Comment by morgancheung** [comment]
sketch 52.2 is ok

**Comment by sergeishere** [comment]
uhh...it seems that it was the Sketch's bug.
