### ISSUE TITLE
Issue with sketch 55

### ISSUE THREAD

**Issue by krdesign** [sergeishere/HandyMenu-SketchPlugin#17]
Does not work with the last version of sketch 55 :(

**Comment by krdesign** [comment]
this is log file 

Error while loading framework 'HandyMenuFramework`

**Comment by sergeishere** [comment]
@krdesign Thanks for feedback! Fixed. You should update the plugin to the new version

**Comment by krdesign** [comment]
Thank you! Your plugin has become indispensable for my workflow. Thanks for doing this for sketch community!
