### ISSUE TITLE
Error while loading framework 'HandyMenuFramework`

### ISSUE THREAD

**Issue by krdesign** [sergeishere/HandyMenu-SketchPlugin#18]
Error while loading framework 'HandyMenuFramework`

In log folder with sketch 55.1 :(

**Comment by sergeishere** [comment]
@krdesign omg 😭. Surprisingly, but the previous version (v5.1) works. Could you try it? https://github.com/sergeishere/HandyMenu-SketchPlugin/releases/download/v5.1/HandyMenu.sketchplugin.zip

**Comment by krdesign** [comment]
Now it works! HandlyManu 5.1 works with sketch 55.1 ;)

**Comment by krdesign** [comment]
Any news about 5.1.1 plugin problem with sketch 55.1? Thanks

**Comment by sergeishere** [comment]
Unfortunately, no news :( Something internal in Sketch has been changed (or broken). I cannot find the problem yet. Probably, we should wait 55.2.

**Comment by sergeishere** [comment]
@krdesign Sketch 55.2 is out. The plugin should work again, I've just tested.

**Comment by krdesign** [comment]
yep ;)
