### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by StudioMastro** [sergeishere/HandyMenu-SketchPlugin#19]
Hi there,

Just installed on my mbp at work and here is not working with new sketch. It seems to work with my personal laptop. What could be? Running RunnerPro e major plugin and latest sketch.

Thanks

**Comment by sergeishere** [comment]
Hi! Unfortunately, Sketch 55.1 breaks the latest plugin version.
But the previous version of the plugin should work: https://github.com/sergeishere/HandyMenu-SketchPlugin/releases/download/v5.1/HandyMenu.sketchplugin.zip

**Comment by StudioMastro** [comment]
I'll try, thanks!

**Comment by StudioMastro** [comment]
Uhm, just tried...no luck for me. 5.1 not working either.

**Comment by sergeishere** [comment]
Have you restarted Sketch after installing the plugin?

**Comment by StudioMastro** [comment]
Got it! Not it works!
