### ISSUE TITLE
Neither 5.1 nor 5.1.1 working in Sketch 55.1 (even with restart)

### ISSUE THREAD

**Issue by jimabout** [sergeishere/HandyMenu-SketchPlugin#20]
Hi Sergei,
I love your plug-in and my life has been tedious since it stopped working in Sketch 55.
I tried your suggestion to install 5.1 and restart. No dice. Same with 5.1.1.  I disabled all plug-ins except for Handy Menu, then tried both versions again with restarts. Nothing. Keyboard short cuts don't work, and selecting Handy Menu > Configure Handy Menu from the Plug-ins menu does nothing.
Any more ideas?

**Comment by sergeishere** [comment]
Hi @jimabout! Unfortunately, no :( Sketch 55.1 breaks the plugin. I am still investigating the problem, but there is no solution yet.

**Comment by sergeishere** [comment]
@jimabout Sketch 55.2 is out. The plugin should work again, I've just tested.

**Comment by jimabout** [comment]
Awesome, thanks for the response(s)!
FWIW I tried using Runner for shortcuts the past few days  but it is just
not as fast for me to use as handy menu. Thanks again!
