### ISSUE TITLE
Not Compatible with Sketch 61

### ISSUE THREAD

**Issue by ihaveabucket** [sergeishere/HandyMenu-SketchPlugin#21]
Any chance we can have this updated to work with the current version of Sketch? This plugin is my life's blood! ^.^

**Comment by sergeishere** [comment]
Hi @ihaveabucket! It should work. I have v61 and the plugin is working well. Could you try to disable other plugins and check?

**Comment by ihaveabucket** [comment]
My apologies - you are absolutely right. I haven't been able to narrow down the conflict, but everything does work just as expected. Cheers, sir!
