### ISSUE TITLE
How to migrate settings to new machine?

### ISSUE THREAD

**Issue by mikecm1** [sergeishere/HandyMenu-SketchPlugin#22]
I have a fresh sketch install on a new computer and transferred all of my plugins, but HandyMenu (amazing by the way) is blank. Very time consuming to set up again, is there a plist file where the shortcut settings are stored?

**Comment by sergeishere** [comment]
Hey @mikecm1. The plugin keeps all setting in the Sketch's User Defaults. Unfortunately, there is no way to transfer shortcuts at the moment. Give me a day and I will make option to export/import settings :)

Thanks for feedback!

**Comment by mikecm1** [comment]
Wow, how’s that for support! Thanks!

**Comment by sergeishere** [comment]
@mikecm1 Just released 5.2 with import/export: `Menu -> Plugins -> HandyMenu -> ...`. Have a nice migration 🙃
