### ISSUE TITLE
Not work sketch version 53

### ISSUE THREAD

**Issue by awharry** [sergeishere/HandyMenu-SketchPlugin#23]
Hello.. @sergehere
This plugin not support for sketch version 53?

**Comment by sergeishere** [comment]
Hey @awharry! The minimum compatible version is 60 now (for Handy Menu v5.2). But you may try to use the v5.1 version https://github.com/sergeishere/HandyMenu-SketchPlugin/releases/tag/v5.1 (Without import/export feature).

**Comment by awharry** [comment]
Solved! Thanks @sergeishere 👍
