### ISSUE TITLE
onRun and onSetup handlers not found

### ISSUE THREAD

**Issue by jasonbirchler** [sergeishere/HandyMenu-SketchPlugin#5]
I am running Sketch 49 and when i run Show Handy Menu and Setup Handy Menu, I see the following errors in the Sketch console:

Error in command script Script at path /Users/<username>/Library/Application Support/com.bohemiancoding.sketch3/Plugins/HandyMenu.sketchplugin/Contents/Sketch/script.js does not contain a handler function named: onStart.

Error in command Show Handy Menu Script at path /Users/<username>/Library/Application Support/com.bohemiancoding.sketch3/Plugins/HandyMenu.sketchplugin/Contents/Sketch/script.js does not contain a handler function named: onRun.

Error in command Setup Handy Menu Script at path /Users/<username>/Library/Application Support/com.bohemiancoding.sketch3/Plugins/HandyMenu.sketchplugin/Contents/Sketch/script.js does not contain a handler function named: onSetup.

I checked script.js and all methods are defined.

**Comment by sergeishere** [comment]
@jasonbirchler Thanks for feedback! I will try to explore this behaviour and will make a fix.

**Comment by bwalowitz** [comment]
I don't understand how to make the menu run? I can drag and drop the plugin actions, but then what?

**Comment by sergeishere** [comment]
@bwalowitz Choose commands you need and click **Save**. Then, press a shortcut for showing the menu (`cmd`+`4`).
