### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by aparajita** [sergeishere/HandyMenu-SketchPlugin#8]
First of all, thank you for this awesome plugin!

- It would be nice to add separators where we want instead of being limited to per plugin, because logical groupings of items might span multiple plugins.

- Search is not that useful now, because in a list of 100 items most of the matches might be out of view. This forces us to scroll to find the matches. True, the matches are highlighted, which helps, but the ideal would be either to show only matching items or to scroll to the first matching item and provide buttons for navigating to the next/previous match.

- Is it possible to include Sketch's menu items? That would make this plugin twice as powerful.

**Comment by sergeishere** [comment]
Hey! Thanks for great feedback! I’ve added it in the backlog. I’m exploring an adding Sketch’s menu items in the handymenu, but don’t have any solution at the moment.

**Comment by aparajita** [comment]
Runner does it so there must be a way.

**Comment by aparajita** [comment]
Thanks for adding separators and better search result visibility in v5.0.

As far as the search UI, maybe you could implement something like the search box that browsers use when searching for text within a page.

**Comment by sergeishere** [comment]
@aparajita I am investigating this solution, thanks for feedback.

**Comment by elaltito** [comment]
Hi there, thanks for the AMAZING plugin!! For me it is **easily** the best and most useful Sketch plugin around!! :)

Quick question: I work between 3 different macs and am constantly tweaking and updating my Handy Menu palettes as my workflow evolves. Is there a way to sync my menu palettes between different macs without me having to recreate them all manually each time? Maybe with an export & import function? Or maybe there is a configuration file somewhere that I can copy and past between my macs with all the menus inside?

Thanks!

**Comment by sergeishere** [comment]
Hi, @elaltito! Thanks for feedback! I will try to implement this function in the next version.

**Comment by sergeishere** [comment]
@elaltito Hey! I am sorry for very long delay. 😬 It's been over a year. But! I have just added the new version with import/export (if you still use the plugin/Sketch) 😎
